- name: Install Git on EC2 Instance
  hosts: all
  become: true
  tasks:
      - name: Update apt packages
        apt:
            update_cache: yes
      - name: Install Git
        apt:
            name: git
            state: present
      - name: Clone the repository
        git:
            repo: https://github.com/andy-a-d-nguyen/code-platoon-assessment-3.git
            version: main # Specify the branch you want to clone
            force: yes # Re-clones the repo if it already exists
      - name: Install Docker prerequisites
        apt:
            name:
                - apt-transport-https
                - ca-certificates
                - curl
                - software-properties-common
            state: present
      - name: Add Docker GPG key
        apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
      - name: Add Docker repository
        apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
            state: present
      - name: Update apt and install Docker
        apt:
            name: docker-ce
            state: present
      - name: Ensure Docker service is running
        service:
            name: docker
            state: started
            enabled:
                - true
      - name: Run Docker Compose
        environment:
            POSTGRES_USER: { { postgres_user } }
            POSTGRES_PASSWORD: { { postgres_password } }
            POSTGRES_DB: { { postgres_db } }
            BACKEND_PORT: { { backend_port } }
            FRONTEND_PORT: { { frontend_port } }
        command: chdir code-platoon-assessment-3/templates/nodejs && docker compose up
