name: Deploy to AWS EC2 using Terraform

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Set Up Terraform
              uses: hashicorp/setup-terraform@v3
            - name: Terraform Init
              run: terraform init
            - name: Terraform Apply
              run: terraform apply -auto-approve
            - name: Get EC2 Public DNS
              run: echo "EC2_PUBLIC_DNS=$(terraform output -raw ec2_connection_url)" >> $GITHUB_ENV
            - name: Print EC2 Public DNS
              run: echo $EC2_PUBLIC_DNS
